### ISSUE TITLE
feat: revocation support for W3C status list (bitstring)

### ISSUE THREAD

**Issue by vivekayanworks** [credebl/platform#818] opened 2024-07-01 07:37 UTC
- [x] Understanding basics of BitStringStatusList
- [x] Change existing type of jsonld credentialFormat to support revocable credentials
- [x] Understanding how we can implement issuance, revocation and verification from existing packages to support typescript (Packages exist in js)
- [ ] BitStringStatusListCredential
  - [ ] Implement a separate API to create BitStringStatusListCredential
    - [ ] Creating encoded bitstring
    - [ ] Signing and storing BitStringStatusListCredential
    - [ ] Hosing the Credential (Optional)
  - [ ] API to retrieve BittringStatusListCredential
  - [ ] API to change status from the bitstring status list
    - [ ] Updating status list
    - [ ] Creating new proof
    - [ ] Updating the hosted BitstringStatusListCredential (Optional)
- [ ] Verification of status of credential (Need to understand)

**Comment by GHkrishna** [comment] 2024-10-23 06:21
Closing this issue, as it was a duplicate of [#164](https://github.com/credebl/credo-controller/issues/164) [#165](https://github.com/credebl/credo-controller/issues/165) [#166](https://github.com/credebl/credo-controller/issues/166) [#167](https://github.com/credebl/credo-controller/issues/167) [#168](https://github.com/credebl/credo-controller/issues/168)

Will create a new issue on platform, once we implement revocation in Credo-controller

**Closed by GHkrishna** 2024-10-23 06:21 UTC
Labels: feature
